services:
  server:
    build:
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: [
    "poetry", "run",
    "uvicorn", "app.main:app","--reload", "--workers", "1", "--host", "0.0.0.0", "--port", "8002"
    ]
    env_file:
      - ./.env
    ports:
      - 8002:8002
    environment:
      - DATABASE_URL=postgresql://postgres:admin@localhost:5432/conference_db
    depends_on:
      - db

  db:
    restart: always
    image: "postgres:latest"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: conference_db
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - /tmp/postgresql/data:/var/lib/postgresql/data